FORMAT: 1A
HOST: http://api.lstn.ltd/

# Lstn

Lstn provides audio representations of articles from the web. Here's a typical API flow:

- client requests an article by providing an article `id`
- backend responds with `HTTP 202` 

*meanwhile...*

- backend fetches full text and metadata of the article (via direct publisher connection, or scraping)
- backend generates an audio representation of the article (via Watson or similar)
- backend transcodes the audio representation as needed (eg. to HLS for iOS)
- backend stores the audio file(s) on a CDN

*later...*

- client requests the article again
- backend responds immediately with the article and its audio representation(s)

A publisher needs to register with Lstn to obtain an authentication token. At this time at publisher can only fetch their own articles.
1
## Articles [/publishers/{publisher}/articles/{article}]

+ Parameters

    + publisher: `the-guardian-uk` (string) - The Lstn-chosen publisher identifier.
    + article: `96bd704-a-news-article` (string) - The publisher-chosen article identifier.

### Retrieve Article [GET]

+ Request (application/json)

    + Headers
    
            Authorization: Bearer 9a7a52a3e8efc2baa12ba2f76bb0e87eccbe26b1

+ Response 200 (application/json)

    Returned when an audio representation is available.
    
    Media may relate to a specific part of the article, as noted by the `role` field. At this time the only supported value is `summary`.

    + Body
    
            {
                "url": "https://publisher.com/.../96bd704-a-news-article.html",
                "title": "A News Article",
                "author": "Jane Doe",
                "summary": "Lorem ipsum dolor [...]",
                "body": "Lorem ipsum dolor sit amet, ei est sumo vitae [...]",
                "published_at": "2000-01-01T00:00:000Z",
                "media": [
                    {
                        "url": "https://cdn.lstn.ltd/.../96bd704-a-news-article.mp3",
                        "type": "audio/mp3",
                        "role": "summary"
                    },
                    {
                        "url": "https://cdn.lstn.ltd/.../96bd704-a-news-article.m3u8",
                        "type": "application/x-mpegurl",
                        "role": "summary"
                    }
                ]
            }

+ Response 202 (application/json)

    Returned when an audio representation has not yet been generated. The client must try again later.
    
    + Body
    
            {
                "code": 123,
                "message": "The article is being processed"
            }

+ Response 400 (application/json)

    Returned when the authentication token is not known.
    
    + Body
    
            {
                "code": 234,
                "message": "The publisher was not recognised"
            }
            
+ Response 404 (application/json)

    Returned when the article was not found.
    
    + Body
    
            {
                "code": 345,
                "message": "The article was not found"
            }
            
+ Response 500 (application/json)

    Returned when an error occured.

    + Body
    
            {
                "code": 456,
                "message": "The article could not be processed"
            }